name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: Backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: Frontend
        run: npm ci

      - name: Build frontend
        working-directory: Frontend
        run: npm run build

      # Docker setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Backend Docker image
      - name: Build backend Docker image
        run: |
          docker build \
            -t saurabhk9919/webchat-backend:latest \
            ./Backend

      # Frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=http://13.201.93.99:5002 \
            -t saurabhk9919/webchat-frontend:latest \
            ./Frontend